# Generated by Django 5.2.5 on 2025-08-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_jobrole_jobroleassignment_trainingrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('role_auto', 'Rol Otomatik'), ('manager', 'Yönetici Talebi'), ('career', 'Kariyer Gelişim Talebi'), ('customer', 'Müşteri Talebi'), ('manual', 'Manuel')], default='role_auto', max_length=20, verbose_name='Kaynak')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('planned', 'Planlandı'), ('done', 'Tamamlandı'), ('cancelled', 'İptal')], default='pending', max_length=12, verbose_name='Durum')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1=En yüksek, 5=En düşük', verbose_name='Öncelik')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('is_open', models.BooleanField(default=True, verbose_name='Açık Kayıt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_training_needs', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_needs', to='trainings.jobroleassignment', verbose_name='Görev Ataması')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_needs', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_needs', to='trainings.jobrole', verbose_name='Görev')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_needs', to='trainings.training', verbose_name='Eğitim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Eğitim İhtiyacı',
                'verbose_name_plural': 'Eğitim İhtiyaçları',
                'indexes': [models.Index(fields=['user', 'is_open'], name='trainings_t_user_id_9c06a9_idx'), models.Index(fields=['training', 'status'], name='trainings_t_trainin_d402aa_idx'), models.Index(fields=['source'], name='trainings_t_source_e8e3de_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'training', 'is_open'), name='uq_open_need_per_user_training')],
            },
        ),
    ]
