# Generated by Django 5.2.5 on 2025-08-26 14:11

import django.db.models.deletion
import django.utils.timezone
import trainings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_trainingneed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Başlangıç')),
                ('end_datetime', models.DateTimeField(verbose_name='Bitiş')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kontenjan')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokasyon')),
                ('instructor_name', models.CharField(blank=True, max_length=150, verbose_name='Eğitmen')),
                ('delivery', models.CharField(choices=[('onsite', 'Sınıf/Onsite'), ('online', 'Online'), ('hybrid', 'Hibrit')], default='online', max_length=10, verbose_name='Sunum Türü')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('scheduled', 'Takvimlendi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='planned', max_length=10, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eğitim Planı',
                'verbose_name_plural': 'Eğitim Planları',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifika', 'verbose_name_plural': 'Sertifikalar'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Katılım', 'verbose_name_plural': 'Katılımlar'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['title'], 'verbose_name': 'Eğitim', 'verbose_name_plural': 'Eğitimler'},
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='training',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='training',
            name='baslangic_tarihi',
        ),
        migrations.RemoveField(
            model_name='training',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='training',
            name='bitis_tarihi',
        ),
        migrations.RemoveField(
            model_name='training',
            name='konum',
        ),
        migrations.RemoveField(
            model_name='training',
            name='zorunlu_mu',
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Bitiş'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seri'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Başarılı mı?'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Kayıtlı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='enrolled', max_length=12, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='training',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kod'),
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma'),
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='training',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (saat)'),
        ),
        migrations.AddField(
            model_name='training',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(default='(Başlıksız Eğitim)', max_length=200, verbose_name='Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=trainings.models.cert_upload_to, verbose_name='Dosya (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Düzenlenme'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='trainings.training', verbose_name='Eğitim'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='trainings.training', verbose_name='Eğitim'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='jobroleassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='trainingneed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='trainingrequirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'training'], name='trainings_c_user_id_5a9aac_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issued_at'], name='trainings_c_issued__106a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'training'], name='trainings_e_user_id_88ed45_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='trainings_e_status_947b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['is_active'], name='trainings_t_is_acti_b110ea_idx'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_plans', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='trainings.trainingneed', verbose_name='Kaynak İhtiyaç'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='trainings.training', verbose_name='Eğitim'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='katilim_tarihi',
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['status'], name='trainings_t_status_415595_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['start_datetime'], name='trainings_t_start_d_6c241d_idx'),
        ),
    ]
