# Generated by Django 5.2.5 on 2025-08-27 15:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_trainingplan_alter_certificate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Video (MP4)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Küçük Resim')),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Süre (sn)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='online_video', to='trainings.training', verbose_name='Eğitim')),
            ],
            options={
                'verbose_name': 'Online Video',
                'verbose_name_plural': 'Online Videolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_seconds', models.FloatField(default=0.0, verbose_name='Son Konum (sn)')),
                ('max_position_seconds', models.FloatField(default=0.0, verbose_name='Maks Konum (sn)')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='trainings.onlinevideo')),
            ],
            options={
                'verbose_name': 'Video İlerleme',
                'verbose_name_plural': 'Video İlerlemeleri',
            },
        ),
        migrations.AddIndex(
            model_name='onlinevideo',
            index=models.Index(fields=['is_active'], name='trainings_o_is_acti_1d050e_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'video'], name='trainings_v_user_id_bc0833_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['completed'], name='trainings_v_complet_e79624_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('user', 'video')},
        ),
    ]
