# Generated by Django 5.2.5 on 2025-08-27 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_onlinevideo_videoprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoleAssignmentQuickAdd',
            fields=[
            ],
            options={
                'verbose_name': 'Kullanıcıya Görev Atama',
                'verbose_name_plural': 'Kullanıcıya Görev Atama',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trainings.jobroleassignment',),
        ),
        migrations.CreateModel(
            name='JobRoleAssignmentQuickList',
            fields=[
            ],
            options={
                'verbose_name': 'Kullanıcılara Atanmış Görevler',
                'verbose_name_plural': 'Kullanıcılara Atanmış Görevler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trainings.jobroleassignment',),
        ),
        migrations.CreateModel(
            name='TrainingPlanAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_attendees', to='trainings.trainingplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plan_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Plan Katılımcısı',
                'verbose_name_plural': 'Plan Katılımcıları',
                'indexes': [models.Index(fields=['plan', 'user'], name='trainings_t_plan_id_db870c_idx')],
                'unique_together': {('plan', 'user')},
            },
        ),
    ]
