# Generated by Django 5.2.5 on 2025-08-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0006_trainingplan_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(blank=True, default='', max_length=50)),
                ('revizyon_tarihi', models.DateField(blank=True, null=True)),
                ('guncelleme_tarihi', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vekalet Tablosu Üst Bilgisi',
                'verbose_name_plural': 'Vekalet Tablosu Üst Bilgisi',
            },
        ),
        migrations.CreateModel(
            name='RoleDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='trainings.jobrole')),
                ('to_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='trainings.jobrole')),
            ],
            options={
                'verbose_name': 'Vekalet Tanımı',
                'verbose_name_plural': 'Vekalet Tanımları',
                'constraints': [models.UniqueConstraint(fields=('from_role', 'to_role'), name='uniq_role_delegation'), models.CheckConstraint(condition=models.Q(('from_role', models.F('to_role')), _negated=True), name='no_self_delegation')],
            },
        ),
    ]
