# Generated by Django 5.2.5 on 2025-08-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationMatrixLink',
            fields=[
            ],
            options={
                'verbose_name': 'Vekalet Tablosu (Matris)',
                'verbose_name_plural': 'Vekalet Tablosu (Matris)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('delegations.delegationdocument',),
        ),
    ]
